In [70]:
import pandas as pd
import numpy as np
from scipy import stats
import datetime as dt

In [71]:
a = np.array([1,2,1,10,5,10,4])

In [72]:
a

array([ 1,  2,  1, 10,  5, 10,  4])

In [73]:
b = np.array([1,2,1,10,5,10,4,100,-3])

In [39]:
a_series = pd.Series(a)

In [40]:
a_series.mode()

0     1
1    10
dtype: int32

In [41]:
a_series.kurtosis()

-1.3878046875

In [42]:
a_series.skew()

0.6767790763704878

In [43]:
stats.skew(a, bias = False)

0.6767790763704881

In [44]:
pd.Series(a).skew()

0.6767790763704878

In [45]:
(np.mean(a)-np.median(a))/np.std(a)

0.19764235376052372

In [46]:
stats.kurtosis(a, fisher=False)

1.6717480468749997

In [49]:
a

array([ 1,  2,  1, 10,  5, 10,  4])

In [48]:
(a- np.min(a))/(np.max(a)-np.min(a))

array([0.        , 0.11111111, 0.        , 1.        , 0.44444444,
       1.        , 0.33333333])

In [52]:
from scipy.stats import zscore

In [55]:
zscore(a)

array([-1.02774024, -0.75104094, -1.02774024,  1.46255342,  0.07905694,
        1.46255342, -0.19764235])

In [57]:
(a - np.mean(a)) / np.std(a)

array([-1.02774024, -0.75104094, -1.02774024,  1.46255342,  0.07905694,
        1.46255342, -0.19764235])

In [74]:
b

array([  1,   2,   1,  10,   5,  10,   4, 100,  -3])

In [81]:
from scipy import stats
stats.median_absolute_deviation(b)

<ipython-input-81-2f5514553bdb>:2: DeprecationWarning: `median_absolute_deviation` is deprecated, use `median_abs_deviation` instead!

To preserve the existing default behavior, use
`scipy.stats.median_abs_deviation(..., scale=1/1.4826)`.
The value 1.4826 is not numerically precise for scaling
with a normal distribution. For a numerically precise value, use
`scipy.stats.median_abs_deviation(..., scale='normal')`.

  stats.median_absolute_deviation(b)


4.4478

In [82]:
q75,q25 =np.quantile(b,0.75) , np.quantile(b,0.25)

In [93]:
print(q75)
print(q25)

10.0
1.0


In [95]:
gap = q75 - q25
print('gap {}'.format(gap))

gap 9.0


In [96]:
upper, lower = q75+gap , q25-gap
print(upper)
print(lower)

19.0
-8.0


In [85]:
[num for num in b if num>upper or num < lower]

[100]

In [90]:
mad_b = np.median([np.abs(num-np.median(b)) for num in b])
mad_b

3.0

In [88]:
[num for num in b if np.abs(num -np.mean(num))/np.std(b)>3]

[]

In [91]:
[num for num in b if np.abs(num- np.median(b)/mad_b>3)]

[10, 5, 10, 100]